Repository appuio/control-api, pull requests merged in 2022-02, with the labels that each got.

#30 Add Organization to scheme
  apis/organization/v1/organization_types.go
Labels: bug

#29 Link OrganizationMembers to Organization with an owner reference
  apiserver/organization/create.go
  apiserver/organization/create_test.go
  apiserver/organization/mock/namespace.go
  apiserver/organization/namespace.go
Labels: enhancement

#32 Increase default resource request/limit for API server
  config/deployment/deployment.yaml
Labels: bug

#31 Remove user id from reference
  apis/v1/organizationmembers_type.go
  apis/v1/user_types.go
  apiserver/organization/create.go
  apiserver/organization/create_test.go
  config/crd/apiextensions.k8s.io/v1/base/appuio.io_organizationmembers.yaml
  config/crd/apiextensions.k8s.io/v1/base/appuio.io_users.yaml
Labels: breaking

#34 Switch user roles from imaginary `edit` to actual `update` verb
  config/user-rbac/basic-user-role.yml
  config/user-rbac/organization-admin-role.yml
Labels: bug

#39 Add Team definition
  apis/v1/team_types.go
  apis/v1/zz_generated.deepcopy.go
  config/crd/apiextensions.k8s.io/v1/base/appuio.io_teams.yaml
Labels: enhancement
