Repository appuio/control-api, pull requests merged in 2022-03, with the labels that each got.

#41 Add teams CRD when running kustomize
  config/crd/apiextensions.k8s.io/v1/kustomization.yaml
Labels: bug

#43 Add teams CRD to default userroles
  config/user-rbac/organization-admin-role.yml
  config/user-rbac/organization-viewer-role.yml
Labels: bug

#44 Give API server permission to create RoleBindings for teams
  apiserver/organization/rolebindings.go
  config/rbac/role.yaml
  config/user-rbac/organization-admin-role.yml
Labels: bug

#37 Only add APPUiO user as members on Organization creation
  apiserver/organization/create.go
  apiserver/organization/create_test.go
  apiserver/organization/mock/rolebindings.go
  apiserver/organization/organization.go
  apiserver/organization/rolebindings.go
  apiserver/organization/rolebindings_test.go
Labels: change

#48 User RBAC
  Makefile
  api.go
  config/deployment/apiserver/apiservice.yaml
  config/deployment/apiserver/deployment.yaml
  config/deployment/apiserver/kustomization.yaml
  config/deployment/apiserver/service.yaml
  config/deployment/controller/deployment.yaml
  config/deployment/controller/kustomization.yaml
  config/deployment/kustomization.yaml
  config/examples/organization.yaml
  config/examples/user.yaml
  config/rbac/apiserver/kustomization.yaml
  config/rbac/apiserver/role.yaml
  config/rbac/apiserver/role_binding.yaml
  config/rbac/apiserver/role_binding_auth_delegator.yaml
  config/rbac/apiserver/service_account.yaml
  config/rbac/controller/kustomization.yaml
  config/rbac/controller/leader_election_role.yaml
  config/rbac/controller/leader_election_role_binding.yaml
  config/rbac/controller/role.yaml
  config/rbac/controller/role_binding.yaml
  config/rbac/controller/service_account.yaml
  config/rbac/kustomization.yaml
  controller.go
  controllers/user_controller.go
  controllers/user_controller_test.go
  go.mod
  go.sum
  main.go
Labels: breaking

#53 Reconcile on owned objects
  controllers/user_controller.go
Labels: ignore

#52 Add option to bind ClusterRoles to all organization members
  Makefile
  config/rbac/controller/role.yaml
  controller.go
  controllers/organization_members_controller.go
  controllers/organization_members_controller_test.go
Labels: enhancement

#54 Adjust OrgMember permissions
  config/rbac/controller/role.yaml
  config/user-rbac/organization-admin-role.yml
  controllers/organization_members_controller.go
Labels: bug

#56 Correctly bind zap flags to controller Cobra command
  controller.go
Labels: bug

#55 Implement validating admission webhook for CR users.appuio.io
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controller.go
  webhooks/user_webhook.go
  webhooks/user_webhook_test.go
Labels: enhancement

#58 Expose controller webhook server certificate directory configuration
  controller.go
Labels: bug

#60 Add controller command line flag to specify the webhook server port
  controller.go
Labels: enhancement

#59 Add logic to setup admission webhooks in local test environment
  .gitignore
  Makefile
  go.mod
  go.sum
  local-env/kind.mk
  local-env/setup-kind.sh
  tools.go
Labels: ignore

#62 Add instructions to register locally running controller with kind local environment in README
  Makefile
  README.md
  local-env/kind.mk
Labels: documentation

#65 Allow User resources with no default organization
  webhooks/user_webhook.go
  webhooks/user_webhook_test.go
Labels: bug
