Repository appuio/control-api, pull requests merged in 2023-04, with the labels that each got.

#145 Remove unneeded `k8s.io/kubernetes` dependency as renovate struggles with it
  go.mod
  go.sum
  webhooks/invitation_webhook.go
  webhooks/invitation_webhook_test.go
Labels: dependency

#146 Create/Update support for BillingEntities
  .goreleaser.yml
  Dockerfile
  api.go
  apiserver/billing/odoostorage/odoo/fake/fake.go
  apiserver/billing/odoostorage/odoo/odoo8/client/clientmock/session.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model/category_id_test.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model/category_ids.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model/nullable.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model/nullable_test.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model/odoo_composite_id.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model/odoo_composite_id_test.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model/partner.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model/tax_id.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model/tax_id_test.go
  apiserver/billing/odoostorage/odoo/odoo8/client/session.go
  apiserver/billing/odoostorage/odoo/odoo8/client/session_test.go
  apiserver/billing/odoostorage/odoo/odoo8/countries/countries.go
  apiserver/billing/odoostorage/odoo/odoo8/countries/countries_test.go
  apiserver/billing/odoostorage/odoo/odoo8/odoo8.go
  apiserver/billing/odoostorage/odoo/odoo8/odoo8_test.go
  apiserver/billing/odoostorage/odoostorage.go
  apiserver/billing/odoostorage/update.go
  countries-export-full.yaml
  countries.yaml
Labels: enhancement

#148 Add metrics that indicate the status of email sending
  controller.go
  controllers/invitation_email_controller.go
  controllers/invitation_email_controller_test.go
  controllers/invitation_email_pending_metric.go
  controllers/invitation_email_pending_metric_test.go
Labels: enhancement

#149 Add permission to create BE; give admin permission over created BE
  apiserver/billing/rbac.go
  apiserver/billing/rbac_test.go
  config/rbac/apiserver/role.yaml
  config/user-rbac/basic-user-role.yml
Labels: enhancement

#150 Allow configuring static BE fields
  api.go
  apiserver/billing/odoostorage/odoo/odoo8/odoo8.go
  apiserver/billing/odoostorage/odoo/odoo8/odoo8_test.go
  apiserver/billing/odoostorage/odoostorage.go
Labels: enhancement

#153 Add status field to billing entities, and persist it to Odoo
  apis/billing/v1/billingentity_types.go
  apis/billing/v1/zz_generated.deepcopy.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model.go
  apiserver/billing/odoostorage/odoo/odoo8/client/model/partner.go
  apiserver/billing/odoostorage/odoo/odoo8/odoo8.go
  apiserver/billing/odoostorage/odoo/odoo8/odoo8_test.go
Labels: enhancement

#151 Allow kubectl to validate CRDs client side
  config/user-rbac/basic-user-role.yml
Labels: bug

#159 Fix service account kubebuilder annotations
  config/rbac/controller/role.yaml
  controllers/billingentity_email_cronjob.go
Labels: bug

#160 Add a command to clean up stale inflight records
  Makefile
  apiserver/billing/odoostorage/odoo/odoo8/client/model/partner.go
  apiserver/billing/odoostorage/odoo/odoo8/odoo8.go
  apiserver/billing/odoostorage/odoo/odoo8/odoo8_test.go
  cleanup.go
  main.go
Labels: enhancement
