Repository appuio/control-api, pull requests merged in 2023-03, with the labels that each got.

#108 Go mod tidy with 1.20
  go.mod
Labels: dependency

#110 Fix reconciliation loop in redeem controller
  controllers/invitation_redeem_controller.go
Labels: bug

#109 Remove expired and redeemed invites
  config/rbac/controller/role.yaml
  controller.go
  controllers/invitation_cleanup_controller.go
  controllers/invitation_cleanup_controller_test.go
Labels: enhancement

#107 Validate invitation targetRefs to prevent privilege escalation
  README.md
  config/webhook/manifests.yaml
  controllers/invitation_redeem_controller.go
  controllers/targetref/targetref.go
  controllers/targetref/targetref_test.go
  local-env/setup-kind.sh
  webhooks/invitation_webhook.go
  webhooks/invitation_webhook_test.go
  webhooks/user_webhook_test.go
Labels: enhancement

#113 Add `omitempty` to Invitation `status.conditions` and `status.targetStatuses`
  apis/user/v1/invitation_types.go
Labels: change

#112 Add Billing instructions to local-env readme and zone example
  config/examples/billing-entity.yaml
  config/examples/zone.yaml
  local-env/README.md
Labels: documentation

#115 Switch passing invitation token from path to url.Values
  apiserver/user/invitation_redeem.go
Labels: breaking

#118 Pass request verb correctly
  apiserver/authwrapper/storage.go
Labels: bug

#119 Fix basic users permission to redeem invitations
  config/user-rbac/basic-user-role.yml
Labels: bug

#117 Adjust logger log level to match debug level
  Makefile
  apiserver/billing/odoostorage/odoo/odoo8/client/debug.go
  controllers/invitation_cleanup_controller.go
  controllers/invitation_redeem_controller.go
  controllers/invitation_token_controller.go
  controllers/org_billingentity_name_cache_controller.go
  controllers/organization_members_controller.go
  controllers/user_controller.go
  webhooks/invitation_webhook.go
  webhooks/user_webhook.go
Labels: enhancement

#116 Add controller for invitation e-mail sending
  controller.go
  controllers/invitation_email_controller.go
  controllers/invitation_email_controller_test.go
  go.mod
  go.sum
  mailsenders/mail_senders.go
Labels: enhancement

#120 Make the creator of an Invitation the owner
  apiserver/user/invitation_storage.go
  apiserver/user/rbac.go
  apiserver/user/rbac_test.go
  config/rbac/apiserver/role.yaml
Labels: enhancement

#123 Render email body in controller
  controller.go
  controllers/invitation_email_controller.go
  controllers/invitation_email_controller_test.go
  mailsenders/mail_senders.go
  mailsenders/renderer.go
  mailsenders/renderer_test.go
Labels: change

#126 Fix storage layer order to expose `redeem` methods
  apiserver/user/invitation_storage.go
Labels: bug

#127 Invitation: Remove `appuio#` prefix from non RBAC objects
  controller.go
  controllers/invitation_redeem_controller.go
  controllers/targetref/targetref.go
  controllers/targetref/targetref_test.go
  webhooks/invitation_webhook.go
Labels: bug

#129 Validate invitation target access using SARs
  Makefile
  config/rbac/controller/role.yaml
  controllers/targetref/targetref.go
  go.mod
  go.sum
  webhooks/invitation_webhook.go
  webhooks/invitation_webhook_test.go
Labels: enhancement

#138 Allow redeemer of an invitation to access (read) it
  controllers/invitation_redeem_controller.go
  controllers/invitation_redeem_controller_rolename_test.go
  controllers/invitation_redeem_controller_test.go
Labels: enhancement

#140 Add Aldebaran Tech as CodeOwners
  CODEOWNERS
Labels: documentation
